#!/usr/bin/env python3
# ==============================================================================
# File:        scripts/fetch_trakt.py
# Repo:        my_TV_Movie
# Path:        scripts/fetch_trakt.py
#
# Version:
#   v1.3.0 (2025-12-16)
#
# Purpose:
#   Pull Trakt watch state + user lists and export a STATIC JSON artifact that the
#   GitHub Pages UI can consume (because Pages cannot call Trakt directly).
#
# What it does:
#   - Reads local TMDB catalog: data/data.json (generated by fetch_tmdb.py)
#   - Calls Trakt API (requires env vars)
#   - Produces:
#       data/trakt.json
#     containing watch-history-derived “watched” flags + last watched timestamps
#     for:
#       - tv shows (by tmdb id)
#       - tv episodes (by tmdb show id + season + episode)
#       - movies (by tmdb id)
#
# Auth (env):
#   - API_TRAKT_CLIENT_ID           (required)
#   - API_TRAKT_ACCESS_TOKEN        (required)  (Bearer token, already-authorized)
# Optional:
#   - API_TRAKT_USERNAME            (optional; for labeling only)
#
# Notes / constraints:
#   - This script does NOT perform OAuth interactive login (keeps it deterministic).
#     You paste/maintain the access token in GitHub Secrets + local env vars.
#   - If Trakt is unavailable, the script exits non-zero (so workflow can flag it),
#     but you can change that policy later if you want “soft fail”.
#
# Output:
#   - data/trakt.json
#
# Logging:
#   - logs/fetch_trakt.log.txt
#   - logs/fetch_trakt_YYYYMMDD_HHMMSS.log.txt
#
# ==============================================================================

from __future__ import annotations

import json
import logging
import os
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import requests


# ==============================================================================
# [PATHS-1.0] Repo paths (stable)
# ==============================================================================
REPO_ROOT = Path(__file__).resolve().parents[1]

DATA_DIR = REPO_ROOT / "data"
CATALOG_PATH = DATA_DIR / "data.json"         # TMDB-built catalog
TRAKT_OUT_PATH = DATA_DIR / "trakt.json"      # Trakt-derived watch state

LOGS_DIR = REPO_ROOT / "logs"

TRAKT_API_BASE = "https://api.trakt.tv"


# ==============================================================================
# [LOG-1.0] Logging
# ==============================================================================
def setup_logging() -> None:
    LOGS_DIR.mkdir(parents=True, exist_ok=True)

    latest_log = LOGS_DIR / "fetch_trakt.log.txt"
    ts = time.strftime("%Y%m%d_%H%M%S", time.localtime())
    stamped_log = LOGS_DIR / f"fetch_trakt_{ts}.log.txt"

    fmt = "%(asctime)s | %(levelname)s | %(message)s"
    datefmt = "%Y-%m-%d %H:%M:%S"

    root = logging.getLogger()
    root.setLevel(logging.INFO)

    for h in list(root.handlers):
        root.removeHandler(h)

    fh_latest = logging.FileHandler(latest_log, encoding="utf-8")
    fh_latest.setLevel(logging.INFO)
    fh_latest.setFormatter(logging.Formatter(fmt, datefmt))

    fh_stamped = logging.FileHandler(stamped_log, encoding="utf-8")
    fh_stamped.setLevel(logging.INFO)
    fh_stamped.setFormatter(logging.Formatter(fmt, datefmt))

    sh = logging.StreamHandler(sys.stdout)
    sh.setLevel(logging.INFO)
    sh.setFormatter(logging.Formatter(fmt, datefmt))

    root.addHandler(fh_latest)
    root.addHandler(fh_stamped)
    root.addHandler(sh)

    logging.info("[fetch_trakt] Logging: %s", latest_log)
    logging.info("[fetch_trakt] Logging: %s", stamped_log)


# ==============================================================================
# [CFG-1.0] Trakt auth + request helpers
# ==============================================================================
@dataclass(frozen=True)
class TraktAuth:
    client_id: str
    access_token: str
    username: str


def load_trakt_auth() -> TraktAuth:
    cid = (os.environ.get("API_TRAKT_CLIENT_ID") or "").strip()
    tok = (os.environ.get("API_TRAKT_ACCESS_TOKEN") or "").strip()
    user = (os.environ.get("API_TRAKT_USERNAME") or "").strip()

    if not cid:
        raise RuntimeError("Missing env: API_TRAKT_CLIENT_ID")
    if not tok:
        raise RuntimeError("Missing env: API_TRAKT_ACCESS_TOKEN")

    return TraktAuth(client_id=cid, access_token=tok, username=user or "unknown")


def trakt_headers(auth: TraktAuth) -> Dict[str, str]:
    # Trakt requires: Content-Type, trakt-api-version, trakt-api-key
    return {
        "Content-Type": "application/json",
        "trakt-api-version": "2",
        "trakt-api-key": auth.client_id,
        "Authorization": f"Bearer {auth.access_token}",
    }


def trakt_get(auth: TraktAuth, path: str, params: Optional[Dict[str, Any]] = None) -> Any:
    url = f"{TRAKT_API_BASE}{path}"
    r = requests.get(url, headers=trakt_headers(auth), params=params or {}, timeout=45)
    if r.status_code >= 400:
        raise RuntimeError(f"Trakt GET failed {r.status_code} for {url}: {r.text[:500]}")
    return r.json()


# ==============================================================================
# [CATALOG-1.0] Load TMDB catalog (data/data.json)
# ==============================================================================
def load_catalog() -> Dict[str, Any]:
    if not CATALOG_PATH.exists():
        raise FileNotFoundError(f"Missing TMDB catalog: {CATALOG_PATH}")
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def index_catalog_tmdb_ids(catalog: Dict[str, Any]) -> Tuple[set[int], set[int], set[Tuple[int, int, int]]]:
    """
    Returns:
      movie_ids: {tmdb_movie_id}
      show_ids:  {tmdb_show_id}
      ep_keys:   {(tmdb_show_id, season, episode)}
    """
    movie_ids: set[int] = set()
    show_ids: set[int] = set()
    ep_keys: set[Tuple[int, int, int]] = set()

    for m in (catalog.get("movies") or []):
        tid = m.get("tmdb_id") or m.get("movie_id")
        if isinstance(tid, int):
            movie_ids.add(tid)

    for s in (catalog.get("shows") or []):
        sid = s.get("tmdb_id") or s.get("show_id")
        if not isinstance(sid, int):
            continue
        show_ids.add(sid)

        for season in (s.get("seasons") or []):
            sn = season.get("season_number")
            if not isinstance(sn, int):
                continue
            for ep in (season.get("episodes") or []):
                en = ep.get("episode_number")
                if not isinstance(en, int):
                    continue
                ep_keys.add((sid, sn, en))

    return movie_ids, show_ids, ep_keys


# ==============================================================================
# [TRAKT-2.0] Fetch history (movies + episodes) and map to catalog
# ==============================================================================
def fetch_movie_history(auth: TraktAuth, max_pages: int = 20, page_size: int = 100) -> List[Dict[str, Any]]:
    """
    /sync/history/movies returns watch history for movies.
    We page until empty or max_pages.
    """
    out: List[Dict[str, Any]] = []
    for page in range(1, max_pages + 1):
        items = trakt_get(auth, "/sync/history/movies", params={"page": page, "limit": page_size})
        if not items:
            break
        out.extend(items)
        logging.info("[trakt] movies history page %s -> %s items (total=%s)", page, len(items), len(out))
    return out


def fetch_episode_history(auth: TraktAuth, max_pages: int = 50, page_size: int = 100) -> List[Dict[str, Any]]:
    """
    /sync/history/episodes returns watch history for individual episodes.
    """
    out: List[Dict[str, Any]] = []
    for page in range(1, max_pages + 1):
        items = trakt_get(auth, "/sync/history/episodes", params={"page": page, "limit": page_size})
        if not items:
            break
        out.extend(items)
        logging.info("[trakt] episodes history page %s -> %s items (total=%s)", page, len(items), len(out))
    return out


def reduce_history_to_latest_by_key_movie(history: List[Dict[str, Any]]) -> Dict[int, str]:
    """
    Returns:
      { tmdb_movie_id: last_watched_at_iso }
    """
    out: Dict[int, str] = {}
    for h in history:
        movie = (h.get("movie") or {})
        ids = (movie.get("ids") or {})
        tmdb = ids.get("tmdb")
        watched_at = h.get("watched_at") or h.get("last_watched_at") or ""
        if isinstance(tmdb, int) and watched_at:
            prev = out.get(tmdb)
            if not prev or watched_at > prev:
                out[tmdb] = watched_at
    return out


def reduce_history_to_latest_by_key_episode(history: List[Dict[str, Any]]) -> Dict[Tuple[int, int, int], str]:
    """
    Trakt episode history records include show+episode objects with ids.
    Returns:
      { (tmdb_show_id, season, episode): last_watched_at_iso }
    """
    out: Dict[Tuple[int, int, int], str] = {}
    for h in history:
        show = (h.get("show") or {})
        ep = (h.get("episode") or {})
        show_ids = (show.get("ids") or {})
        ep_ids = (ep.get("ids") or {})

        tmdb_show = show_ids.get("tmdb")
        season = ep.get("season")
        number = ep.get("number")
        watched_at = h.get("watched_at") or ""

        if isinstance(tmdb_show, int) and isinstance(season, int) and isinstance(number, int) and watched_at:
            key = (tmdb_show, season, number)
            prev = out.get(key)
            if not prev or watched_at > prev:
                out[key] = watched_at
    return out


# ==============================================================================
# [OUT-1.0] Build trakt.json output structure
# ==============================================================================
def build_trakt_output(
    auth: TraktAuth,
    catalog_meta: Dict[str, Any],
    catalog_movie_ids: set[int],
    catalog_show_ids: set[int],
    catalog_ep_keys: set[Tuple[int, int, int]],
    movie_latest: Dict[int, str],
    ep_latest: Dict[Tuple[int, int, int], str],
) -> Dict[str, Any]:
    built_at = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())

    # Movies: mark watched if TMDB id exists in catalog and in history
    movies: Dict[str, Any] = {}
    for tmdb_id, watched_at in movie_latest.items():
        if tmdb_id in catalog_movie_ids:
            movies[str(tmdb_id)] = {"watched": True, "last_watched_at": watched_at}

    # Episodes: mark watched if exists in catalog
    episodes: Dict[str, Any] = {}
    for (show_tmdb, season, ep), watched_at in ep_latest.items():
        if (show_tmdb, season, ep) in catalog_ep_keys:
            episodes[f"{show_tmdb}:{season}:{ep}"] = {
                "watched": True,
                "last_watched_at": watched_at,
                "show_tmdb_id": show_tmdb,
                "season": season,
                "episode": ep,
            }

    # Shows: derive show watched summary (any watched episode)
    shows: Dict[str, Any] = {}
    # Build show -> latest watched timestamp across episodes
    show_latest: Dict[int, str] = {}
    for key, info in episodes.items():
        sid = info["show_tmdb_id"]
        ts = info["last_watched_at"]
        prev = show_latest.get(sid)
        if not prev or ts > prev:
            show_latest[sid] = ts

    for sid, ts in show_latest.items():
        if sid in catalog_show_ids:
            shows[str(sid)] = {"has_watched": True, "last_watched_at": ts}

    return {
        "meta": {
            "version": "v1.3.0",
            "built_at": built_at,
            "trakt_user": auth.username,
            "source_catalog": {
                "catalog_version": (catalog_meta.get("version") or ""),
                "catalog_built_at": (catalog_meta.get("built_at") or ""),
                "shows": int(catalog_meta.get("shows") or 0),
                "movies": int(catalog_meta.get("movies") or 0),
            },
            "counts": {
                "shows_marked": len(shows),
                "episodes_marked": len(episodes),
                "movies_marked": len(movies),
            },
        },
        "shows": shows,         # keyed by tmdb show id (string)
        "episodes": episodes,   # keyed by "show:season:ep"
        "movies": movies,       # keyed by tmdb movie id (string)
    }


# ==============================================================================
# [MAIN-1.0] Main
# ==============================================================================
def main() -> None:
    setup_logging()

    # Validate inputs
    auth = load_trakt_auth()
    catalog = load_catalog()

    catalog_meta = (catalog.get("meta") or {})
    movie_ids, show_ids, ep_keys = index_catalog_tmdb_ids(catalog)

    logging.info("[fetch_trakt] Catalog: movies=%s shows=%s episodes=%s", len(movie_ids), len(show_ids), len(ep_keys))
    logging.info("[fetch_trakt] Trakt user: %s", auth.username)

    # Fetch history
    movie_hist = fetch_movie_history(auth)
    ep_hist = fetch_episode_history(auth)

    # Reduce to latest watch timestamps by key
    movie_latest = reduce_history_to_latest_by_key_movie(movie_hist)
    ep_latest = reduce_history_to_latest_by_key_episode(ep_hist)

    logging.info("[fetch_trakt] History reduced: movies=%s episodes=%s", len(movie_latest), len(ep_latest))

    # Build output
    out = build_trakt_output(
        auth=auth,
        catalog_meta=catalog_meta,
        catalog_movie_ids=movie_ids,
        catalog_show_ids=show_ids,
        catalog_ep_keys=ep_keys,
        movie_latest=movie_latest,
        ep_latest=ep_latest,
    )

    DATA_DIR.mkdir(parents=True, exist_ok=True)
    TRAKT_OUT_PATH.write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")

    logging.info("[fetch_trakt] Wrote: %s (%s bytes)", TRAKT_OUT_PATH, TRAKT_OUT_PATH.stat().st_size)
    logging.info(
        "[fetch_trakt] DONE | shows_marked=%s episodes_marked=%s movies_marked=%s",
        out["meta"]["counts"]["shows_marked"],
        out["meta"]["counts"]["episodes_marked"],
        out["meta"]["counts"]["movies_marked"],
    )


if __name__ == "__main__":
    main()
